// React/lab4-5/my-app/src/Components/MovieDetails.js
import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";

function MovieDetails() {
    const [movie, setMovie] = useState("");
    const location = useLocation();
    console.log(location.state.id);
    useEffect(() => {
        setMovie(location.state);
    }, []);
    return (
        <div className="container">
            <div className="row">
                <div className="col-6">
                    <img src={`https://image.tmdb.org/t/p/w500/${movie.poster_path}`} alt="" />
                </div>
                <div className="col-6">
                    <h2>{movie.title}</h2>
                    <p>{movie.overview}</p>
                </div>
            </div>
        </div>
    );
}

export default MovieDetails;

// Angular/my-app/src/app/Components/movie-details/movie-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { MoviesService } from '../../Services/movies.service';
import { IGenre, IMovie } from '../../Model/Movies';

@Component({
  selector: 'app-movie-details',
  templateUrl: './movie-details.component.html',
  styleUrls: ['./movie-details.component.css'],
})
export class MovieDetailsComponent implements OnInit {
  private movieID: number = 0;
  currMovie: IMovie = {} as IMovie;
  genreList: IGenre[] = [];

  constructor(
    private activatedRoute: ActivatedRoute,
    private moviesService: MoviesService
  ) {}

  ngOnInit(): void {
    this.movieID = Number(this.activatedRoute.snapshot.paramMap.get('id'));
    this.moviesService.getMovieByID(this.movieID).subscribe((movie) => {
      this.currMovie = movie;
    });

    this.moviesService.getMovieGenre().subscribe((movieGenres) => {
      this.genreList = movieGenres;
      console.log(this.genreList);
    });
  }
}

<div class="container">
  <div class="row">
    <div class="col-6">
      <img
        src="https://image.tmdb.org/t/p/w500/{{ currMovie.poster_path }}"
        alt=""
      />
    </div>
    <div class="col-5">
      <h3>{{ currMovie.title }}</h3>
      <p>{{ currMovie.overview }}</p>
      <p *ngFor="let genre of currMovie.genre_ids">{{ genre }}}</p>
    </div>
  </div>
</div>
